#!/usr/bin/env bash
# in this file we print 10 times the word "Best School"
for i in {1..100}
do
   
   if [ $(( i % 3 )) -eq 0 ] && [ $(( i % 5 )) -eq 0 ]
   then 
      echo "FizzBuzz"
   elif [ $(( i % 3 )) -eq 0 ]
   then 
      echo "Fizz"
   elif [ $(( i % 5 )) -eq 0 ]
   then
      echo "Buzz"
   else 
      echo "$i"
   fi
done 
