#!/usr/bin/env bash
# in this file we print 10 times the word "Best School"
i=1
while [ $i -le 9 ]
do
  if [ $i -eq 9 ]
  then
    printf "%s\n%s\n" "Best School" "Hi"
  fi
  echo "Best School"
  i=$(( i + 1 ))
done
