#!/usr/bin/env bash
# in this file we print 10 times the word "Best School"
i=0
while [ $i -le 12 ]
 do
  echo "Hour: $i"
  i=$(( i + 1 ))
  j=1
  while [ $j -le 59 ]
   do
     echo "$j"
     j=$(( j + 1))
   done 
done
