#!/usr/bin/env bash
# in this file we print 10 times the word "Best School"
if [ -f school ]; then
    echo "school file exists"
  if [ -s school ]; then
    echo "school file is empty"
  else
    echo "school file is not empty"
  fi
  if [ -f school ]; then
    echo "school is a regular file"
  fi
else 
    echo "school file does not exist"
fi
