#!/usr/bin/env bash
# A script that manages a process of printing

var1=$1

start() {
    ./manage_my_process &
    echo $! > /var/run/myscript.pid
    echo "manage_my_process started" 
}

stop() {
    pkill -f manage_my_process
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}

restart() {
    pkill -f manage_my_process
    rm /var/run/my_process.pid
    ./manage_my_process
    echo $$ > /var/run/myscript.pid
    echo "manage_my_process restarted""
}

case $var1 in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       restart
       ;;
  
    *) echo "Usage: manage_my_process {start|stop|restart}"
	;; 

esac
