#!/usr/bin/env bash
# In this script we print the word To infinity and beyond indefinitely
echo $$ > /var/run/myscript.pid
while :
do
  echo "To infinity and beyond"
  trap "echo I hate the kill command" SIGTERM
  trap "echo Y U no love me?!" SIGINT
  trap "rm /var/run/myscript.pid" SIGQUIT SIGTERM 
  sleep 2
done
